/* Copyright (c) 2026 James Honiball (KC3TFZ)
 * 
 * This file is part of VUURWERK and is dual-licensed:
 *   1. GPL v3 (when distributed as part of the VUURWERK firmware)
 *   2. Commercial license available from the author
 * 
 * You may not extract, repackage, or redistribute this file 
 * independently under any license other than GPL v3 as part 
 * of the complete VUURWERK firmware, without written permission
 * from the author.
 */

#include "ctcss_lead.h"
#include "drivers/bsp/bk4819.h"
#include "features/radio/radio.h"

CtcssLead_t gCtcssLead = { .active = false, .countdown = 0 };

void CTCSS_LEAD_Init(void)
{
	gCtcssLead.active    = false;
	gCtcssLead.countdown = 0;
}

void CTCSS_LEAD_Start(void)
{
	// Only use tone lead if channel has CTCSS or DCS enabled
	if (gCurrentVfo->pTX->CodeType == CODE_TYPE_OFF) {
		gCtcssLead.active    = false;
		gCtcssLead.countdown = 0;
		return;
	}

	// Mute mic audio — CTCSS tone still transmits (generated by BK4819 hardware)
	BK4819_EnterTxMute();

	gCtcssLead.active    = true;
	gCtcssLead.countdown = TONE_LEAD_TICKS;
}

void CTCSS_LEAD_Process(void)
{
	if (!gCtcssLead.active)
		return;

	if (gCtcssLead.countdown > 0)
		gCtcssLead.countdown--;

	if (gCtcssLead.countdown == 0) {
		// Tone lead period complete — unmute mic audio
		BK4819_ExitTxMute();
		gCtcssLead.active = false;
	}
}

void CTCSS_LEAD_Stop(void)
{
	if (gCtcssLead.active) {
		// PTT released before lead-in finished — ensure mic is unmuted
		BK4819_ExitTxMute();
	}
	gCtcssLead.active    = false;
	gCtcssLead.countdown = 0;
}